name: catalogo_jogos
description: Catálogo pessoal de jogos para Desenvolvimento Mobile I.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
